### ISSUE TITLE
Line chart labels disappearing off end of chart. 

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#15]
In the line chart, the labels of each of the lines is disappearing on the right. See here for the problem: http://www.abc.net.au/dat/news/interactives/graphics/gt-turnbull-vs-abbott-3-months/#desktop

**Comment by blakebutcher** [comment]
We can use the `marginRight` content configuration to increase the space for the labels. I've also updated it so mobile will use 90% of the marginRight value (instead of being hardcoded to 45).

Ideally it would work out the space required based on the content itself. I've created #27 for that.

Also we would want the option of showing the labels in a legend instead of on the right of the graph. Particularly for mobile. I've created #26 for that.
