### ISSUE TITLE
In the mobile view, the dates just appear as 16 instead of 2016

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#18]
On the mobile configuration, the dates just appear as "16" which means 2016 but would be incomprehensible to a reader. See example here: http://www.abc.net.au/dat/news/interactives/graphics/gt-turnbull-vs-abbott-3-months/#mobile

**Comment by blakebutcher** [comment]
This seems to be intentional behaviour for the mobile view, so I'm hesitant to change it. I'm guessing they did it to save space.

It seems like the real problem in the example is that it shows "16" multiple times with no differentiation. When it would make more sense for it to show the quarter or month of that gridline. I'll look into what options we have to change that.

**Comment by blakebutcher** [comment]
The default time format has changed, so this is no longer a problem (see #21). You can also use `timeFormatSmall` to override the default time format for mobile.
