### ISSUE TITLE
Provide feedback to user when deploying changes

### ISSUE THREAD

**Issue by mattliddy** [abcnews/dailygraphics#37]
On the chart builder, can we give the user feedback after a change to the chart is deployed?

Getting a message like "Successfully deployed" would be re-assuring.

**Comment by blakebutcher** [comment]
@mattliddy At the moment I'm not confident that I can reliably report if the graphic has successfully deployed so I've updated Chart Builder so that the server commands and outputs are exposed on the page instead of automatically redirecting back.

Its probably not what you were wanting but I think its a step in the right direction and provides useful debugging information if something does go wrong.

**Comment by blakebutcher** [comment]
I've improved this further so that the "Continue" button is colour coded based on the shell output. So if everything seems ok it shows as green, otherwise as red.
