### ISSUE TITLE
Coloured labels need to be darkened to make them AA compliant

### ISSUE THREAD

**Issue by BenSpraggon** [abcnews/dailygraphics#43]

**Comment by blakebutcher** [comment]
The labels on line charts should be getting dynamically darkened to be AA accessible. That will only be the case on line charts that were created (or had their templates redeployed) since yesterday.

If there are older line charts that need to be fixed it should just be a case of redeploying the template via Chart Builder's advanced mode.

I still need to update each of the other chart types one by one...

**Comment by blakebutcher** [comment]
Slopegraph is now using accessible coloured labels

**Comment by blakebutcher** [comment]
These should all be accessible now.
