### ISSUE TITLE
Locator map does not work, even using sheet template data

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#9]

**Comment by blakebutcher** [comment]
The original documentation explains this as:

> It will not create production-ready maps, but it will quickly generate a code-based starting point for a map project.

https://github.com/abcnews/dailygraphics#creating-locator-maps

**Comment by blakebutcher** [comment]
By default it should display a map of Nepal. The reason it doesn't is that the geodata.json is not copied over by the build process.

But there is not much point in changing the build process because there would not be any way for a Chart Builder user to change that data. And I don't think that managing the geodata in the Google Sheet will help us much here.

Currently the "Locator map" option is hidden under the advanced mode of Chart Builder. I think we should consider either removing it totally, or setting it as low priority and revisit it much later on.
